### ISSUE TITLE
Animal behavior

### ISSUE THREAD

**Issue by jojona** [jojona/AGI17_perkunas#46]

**Comment by Zinzano** [comment]
Eating, and life time behavior

**Comment by jojona** [comment]
High priority: Eat apples, walk around
Medium Priority: Flocking behaviour 
Low priority: Fleeing behaviour from fire / controller / player
Low priority: Interacting with rain and Shadows
Low priority: (Depends on difficulty in Unity) Interact with cliffs / flat ground
